name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wasmtime
      run: |
        INSTALLER=./wasmtime-install.sh
        WASMTIME_VERSION=v15.0.1
        curl https://wasmtime.dev/install.sh -L --output ${INSTALLER}
        chmod a+x ${INSTALLER}
        ${INSTALLER} --version ${WASMTIME_VERSION}
        sudo cp ${HOME}/.wasmtime/bin/wasmtime /usr/bin/wasmtime
    - name: install wasi-sdk
      run: |
        curl https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20/wasi-sdk-20.0-linux.tar.gz -L --output wasi-sdk-20.0-linux.tar.gz
        tar -C /usr/local/lib -xvf wasi-sdk-20.0-linux.tar.gz
    - name: make
      run: make
    - name: make check
      run: make check
